# fly.toml app configuration file generated for coolmovies on 2026-05-22T03:11:22-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coolmovies'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  PRODUCTION = 'true'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/api/user/count'

[[vm]]
  memory = '512mb'
  cpus = 1
  memory_mb = 512
